//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemEX.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string The_name_of_the_country { get; set; }
        public string English_name { get; set; }
        public string Code { get; set; }
        public short Code2 { get; set; }
    }
}
