//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemEX.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int idEvent { get; set; }
        public int Number { get; set; }
        public string Events1 { get; set; }
        public string DATE { get; set; }
        public int DAYS { get; set; }
        public int CITY { get; set; }
    }
}
