//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemEX.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public byte Number { get; set; }
        public string Events1 { get; set; }
        public string DATE { get; set; }
        public byte DAYS { get; set; }
        public byte CITY { get; set; }

        public string Background
        {
            get
            {
                return "#fff";
            }
        }

        public string Sort
        {
            get
            {
                var sort = this.Events1;
                return sort;
            }
        }

        public string ImgPath
        {
            get
            {
                var path = "pack://application:,,,/Resources/" + this.Number + ".png";
                return path;
            }
        }
	}
}
